Core functionality in place

diff --git a/dot b/dot
--- a/dot
+++ b/dot
@@ -1,39 +1,22 @@
 #!/usr/bin/env bash
 # vim: ft=bash tw=80
-#
-#-------------------------------------------------------------------------------
-# General idea:
-#  `dot add` moves a local dot{file,dir} to a directory here
-#     - optionally under a subdirectory to serve as a "tag"
-#     - e.g., the same file can have slight differences across tags
-#     - just use `nvim -d` to manage differences between tags
-#     - helps for macOS bashrc vs. arch bashrc
-#  `dot deploy` replaces the current file with the one from here
-#     - don't know if I want to do it with symlinks or not
-#     - before any destructive action is taken, saves backup of current file
-#  * safe:
-#     - in-place, versioned backups before replacing any file
-#  * easy:
-#     - auto-completion
-#     - flexible organizational system
+# shellcheck disable=SC2155,SC2016,SC2295
 #
 #--- TODO ----------------------------------------------------------------------
-# [ ] Validate that entries in ./dotfiles/ match up with entires in ./database
-#
-#-------------------------------------------------------------------------------
-# Thinkies:
-# Validation
-#  - when adding, `src' may not already exist
-#  - when adding, `dst` may not be a symlink already
+# [ ] trap rollback on error
+#     - don't want to get half way through moving directories/files into the
+#       repo, crash, and not save the new database back
+#     - each time an action is taken, push a corresponding rollback command?
+#     - i.e., running ['mv', 'foo', 'bar'], pushes ['mv', 'bar', 'foo']
+# [ ] bash completion
 #
 #-------------------------------------------------------------------------------
 
 set -e
 
 declare -g  THIS=$( realpath "${BASH_SOURCE[0]}" )
-declare -g  PROGDIR=$( cd "$(dirname "${THIS}")" ; pwd )
+declare -g  PROGDIR="${THIS%/*}"
 declare -g  DATABASE="${PROGDIR}/database"
-
 declare -gA MAP=()   # { source -> dest }
 #declare -gA RMAP=()  # { dest -> source[] }
 #declare -g  SOURCE_LIST=
@@ -44,13 +27,15 @@ declare -gA MAP=()   # { source -> dest }
 touch "${DATABASE}" -a
 mkdir -p "${PROGDIR}/dotfiles"
 
+declare -g hg="hg -R ${PROGDIR}"
+
 # PROGDIR/
 #  +-- database
 #  `-- dotfiles/
 #       +-- bash/
 #       |    `-- .bashrc
 #       `-- nvim/
-    
+
 function usage {
    declare -i status="$1"
    cat <<EOF
@@ -69,85 +54,159 @@ exit "$status"
 
 function load_data {
    local src dst
-
-   declare -p DATABASE
-   cat $DATABASE
-
-   while IFS=$'\t' read -r dst src ; do
-      MAP["${src}"]="${dst}"
-   done < "${DATABASE}"
+   while IFS=$'\t' read -r src dst ; do
+      MAP["$src"]="$dst"
+   done < "$DATABASE"
 }
 
 
-function write_data {
+# TODO: can be a bit risky, gotta make sure not to truncate the file if error.
+function store_data {
+   local src dst
    for src in "${!MAP[@]}" ; do
-      local dst="${MAP["${src}"]}"
-      printf '%s\t%s\n' "${src}" "${dst}"
+      local dst="${MAP["$src"]}"
+      printf '%s\t%s\n' "$src" "$dst"
    done > "${DATABASE}"
 }
 
 
-#function new_src_list {
-#   local name="__SOURCE_LIST_$(( ++_SOURCE_LIST_IDX ))"
-#   declare -ga "$name"
-#   declare -g SOURCE_LIST="$name"
-#}
+function validate_add {
+   local dst="$1"  # where the file will go: the destination
+   local src="$2"  # where it comes from: ./dotfiles/
 
+   if [[ ! $dst ]] ; then
+      printf 'missing dst.\n'
+      exit 1
+   fi
 
-function add_entry {
-   # `dot add ~/.bashrc bash/laptop/.bashrc`
-   #          ^- dst    ^- src
-   #
-   # Must...
-   #  strip leading ${HOME}
-   #  fail if not found
-
-   # `src' and `dst' appear flipped, but where the file ORIGINATES is where it
-   # must be deployed back to: the destination.
-   local dst="$1"
-   local src="$2"
-
-   if [[ ! $dst || ! -f $dst ]] ; then
-      printf 'File does not exist\n'
+   if [[ ! -f $dst && ! -d $dst ]] ; then
+      printf 'dst does not exist\n'
       printf '   %s\n'  "$dst"
       exit 1
    fi
 
-   if [[ $dst =~ ^[/~] ]] ; then
-      printf 'Destination may not be absolute. Is relative to\n'
-      printf '   %s\n'  "${PROGDIR}"
+   if [[ -L $dst ]] ; then
+      printf 'dst already a symlink:\n'
+      stat --printf '%N\n'  "$dst"
       exit 1
    fi
 
-   local relative_dst="${dst#$HOME/}"
-   if [[ $dst == "${relative_dst}" ]] ; then
-      printf '[dot] only owns files/dirs under $HOME/\n'
-      printf '  %s\n'  "$dst"
+   if [[ ! "${PWD}/${dst}" == ${HOME}* ]] ; then
+      printf 'dst must be under %s\n'  "$HOME"
       exit 1
    fi
 
-   # Hoping to catch some errors early, save time before parsing the data file.
-   load_data
-
-   if [[ "${MAP[$src]}" ]] ; then
-      printf '[dot] already owns ~/%s\n'  "${relative_dst}"
-      printf '   %s\n'  "${MAP[$src]}" 
+   if [[ ! $src ]] ; then
+      printf 'missing src.\n'
+      exit 1
    fi
 
-   printf 'Assuming ownership of\n'
-   printf '   ~/%s\n'  "$relative_dst"
-   printf 'as\n'
-   printf '   %s\n'  "${relative_src}"
+   if [[ $src =~ ^[/~] ]] ; then
+      printf 'source must be relative\n'
+      exit 1
+   fi
 }
 
 
-function list_tree {
-   # `cd` just kinda nice for better formatting with `tree`. Shows directories
-   # relative to ./dotfiles/ instead of wherever you were in the filesystem.
-   ( cd "${PROGDIR}" && tree --prune --noreport -a -I .hg dotfiles ) || {
-      printf 'Unable to cd to %s.\n' "$PROGDIR"
+function validate_database {
+   local -a deleted=()
+
+   local _k
+   for _k in "${!MAP[@]}" ; do
+      local _v="${MAP["$_k"]}"
+      deleted["$_k"]="$_v"
+   done
+
+   local src
+   for src in "${!MAP[@]}" ; do
+      if [[ -e "${PROGDIR}/dotfiles/${src}" ]] ; then
+         unset 'deleted[$src]'
+      fi
+   done
+
+   if (( ${#deleted[@]} )) ; then
+      printf 'these are in the database, but not the filesystem\n'
+      printf ' %s\n'  "${deleted[@]}"
       exit 1
-   }
+   fi
+}
+
+
+function cmd_add {
+   local dst="$1"
+   local src="$2"
+
+   validate_add "$dst" "$src"
+   load_data
+
+   local abs_src  abs_dst  rel_dst
+   abs_src="${PROGDIR}/dotfiles/${src}"
+   abs_dst=$( realpath "$dst" )
+   rel_dst="${abs_dst#${HOME}/}"
+
+   if [[ "${MAP[$src]}" ]] ; then
+      printf 'mapping already exists from\n'
+      printf ' %s -> %s\n'  "$src"  "${MAP[$src]}"
+      exit 1
+   fi
+
+   if [[ -e $abs_src ]] ; then
+      printf 'src already exists.\n'
+      ls -l "$abs_src"
+   fi
+
+   printf 'make local backup...\n'
+   cp -v --backup='existing' "$abs_dst" "${abs_dst}.bak"
+
+   printf '\nassume ownership...\n'
+   mkdir -vp "${abs_src%/*}"
+   mv -vn "$abs_dst" "$abs_src"
+
+   printf '\nlink back...\n'
+   ln -v "$abs_src" "$abs_dst"
+
+   # shellcheck disable=SC2086
+   $hg -v add "$abs_src"
+
+   # shellcheck disable=SC2086
+   $hg -v commit -m "Add ${rel_dst} as ${dst}"
+
+   store_data
+}
+
+
+function cmd_deploy {
+   local src="$1"
+
+   if [[ ! $src ]] ; then
+      printf 'missing src.\n'
+      exit 1
+   fi
+
+   load_data
+   local dst="${MAP[$src]}"
+
+   if [[ ! $dst ]] ; then
+      printf 'src not found in database\n'
+      exit 1
+   fi
+
+   local abs_src="${PROGDIR}/dotfiles/${src}"
+   local abs_dst="${HOME}/${dst}"
+
+   if [[ ! -e $abs_src ]] ; then
+      printf 'src file seems not to exist at...\n'
+      printf ' %s\n'  "$abs_src"
+      exit 1
+   fi
+
+   if [[ -L $abs_src ]] ; then
+      printf 'dst already a symlink:\n'
+      stat --printf '%N\n'  "$dst"
+      exit 1
+   fi
+
+   ln -sv --backup='numbered' "$abs_src" "$abs_dst"
 }
 
 
@@ -155,26 +214,29 @@ case "$1" in
    '' | -h | --help)
       usage 0 ;;
 
+   # Regular commands.
    add)
-      shift ; add_entry "$@" ;;
+      cmd_add "${@:2}" ;;
 
    deploy)
-      shift ; deploy_entry "$@" ;;
+      cmd_deploy "${@:2}" ;;
 
-   ls | tree)
-      shift ; list_tree "$@" ;;
+   tree)
+      cd "$PROGDIR"
+      tree --prune --noreport -a -I .hg dotfiles ;;
 
+   ls)
+      sort -k2 "${DATABASE}" | column -t ;;
 
-   ## While testing.
-   t) load_data ; declare -p MAP ;;
+   validate)
+      validate_database ;;
 
+   # Repository commands.
+   hg)
+      hg -R "${PROGDIR}" "${@:2}" ;;
 
-   *) if [[ -f $1 || -d $1 ]] ; then
-         printf 'No command specified. Perhaps you meant:\n'
-         printf "   \`${THIS} add  ${1/$HOME/'~'}  $2\`\n"
-      else
-         printf 'Unknown option: %s\n' "$1"
-      fi
-      exit 1
-      ;;
+   #diff)
+   #   hg -R "${PROGDIR}" diff "${@:2}" ;;
+
+   *) usage 1 ;;
 esac
